language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - export PYTHONPATH=.
script:
  - python djanalytics/tests/django-admin.py test --settings=djanalytics.tests.settings
notifications:
  email:
    recipients:
      - tech@analytehealth.com

